# config/__init__.py

from .settings import (
    DATABASE_CONFIG,
    GEMINI_API_KEY,
    APP_TITLE,
    APP_DESCRIPTION,
    APP_VERSION,
    CORS_ORIGINS,
    DEFAULT_SEARCH_RADIUS_KM,
    MAX_SEARCH_RADIUS_KM,
    MAX_CONVERSATION_HISTORY
)

__all__ = [
    'DATABASE_CONFIG',
    'GEMINI_API_KEY',
    'APP_TITLE',
    'APP_DESCRIPTION', 
    'APP_VERSION',
    'CORS_ORIGINS',
    'DEFAULT_SEARCH_RADIUS_KM',
    'MAX_SEARCH_RADIUS_KM',
    'MAX_CONVERSATION_HISTORY'
]